plugins {
    id "com.android.application"
}

android {
    namespace "com.wato.questopenxr"
    compileSdk 32
    ndkVersion "26.1.10909125"

    defaultConfig {
        applicationId "com.wato.questopenxr"
        minSdk 29
        targetSdk 32
        versionCode 1
        versionName "0.1"

        ndk {
            abiFilters "arm64-v8a"
        }
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                cppFlags "-std=c++17"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    // NativeActivity app -- no Java/Kotlin sources, no res/ resources needed.
    sourceSets {
        main {
            manifest.srcFile "src/main/AndroidManifest.xml"
        }
    }
}
