services:
  teleop:
    build:
      context: ..
      dockerfile: docker/teleop/teleop.Dockerfile
      cache_from:
        - "${TELEOP_IMAGE:?}:${TAG}"
        - "${TELEOP_IMAGE:?}:main"
    image: "${TELEOP_IMAGE:?}:${TAG}"
    network_mode: host
    profiles: [deploy, develop]
    command: sleep infinity
    volumes:
      - ${MONO_DIR}/autonomy/teleop:/root/ament_ws/src/teleop
      - ${MONO_DIR}/autonomy/teleop/quest_teleop/certs:/certs:ro