version: "3.8"
services:
  foxglove:
    build: &foxglove
      context: ..
      dockerfile: docker/infrastructure/foxglove/foxglove.Dockerfile
      cache_from:
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:main"
    image: "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
    profiles: [deploy, develop]
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=${FOXGLOVE_BRIDGE_PORT:?}"]
    ports:
      - target: ${FOXGLOVE_BRIDGE_PORT:?}
        published: ${FOXGLOVE_BRIDGE_PORT:?}
        protocol: tcp
    volumes:
      # Mount as a ROS package so Foxglove Bridge can resolve package:// URLs
      - ${MONO_DIR}/autonomy/URDF/arm_assembly_4_description:/opt/ros/humble/share/arm_assembly_4_description:ro
    environment:
      # Ensure ROS can find the package
      - ROS_PACKAGE_PATH=/opt/ros/humble/share
      - AMENT_PREFIX_PATH=/opt/ros/humble:/opt/ros/humble/share/arm_assembly_4_description