x-simulation_isaac_volumes: &simulation_isaac_volumes
  - /tmp/.X11-unix:/tmp/.X11-unix:rw
  - ${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:rw
  - ${MONO_DIR}:/workspace/humanoid:rw
  - /dev:/dev
  - /run/udev:/run/udev:ro
  - ${HF_HOME:-${HOME}/.cache/huggingface}:/root/.cache/huggingface:rw
  - ${ISAAC_SIM_CACHE_DIR}/cache/kit:/isaac-sim/kit/cache:rw
  - ${ISAAC_SIM_CACHE_DIR}/cache/ov:/root/.cache/ov:rw
  - ${ISAAC_SIM_CACHE_DIR}/cache/pip:/root/.cache/pip:rw
  - ${ISAAC_SIM_CACHE_DIR}/cache/glcache:/root/.cache/nvidia/GLCache:rw
  - ${ISAAC_SIM_CACHE_DIR}/cache/computecache:/root/.nv/ComputeCache:rw
  - ${ISAAC_SIM_CACHE_DIR}/logs:/root/.nvidia-omniverse/logs:rw
  - ${ISAAC_SIM_CACHE_DIR}/data:/root/.local/share/ov/data:rw
  - ${MONO_DIR}/autonomy/teleop/quest_teleop/certs:/certs:ro

x-simulation_isaac_env: &simulation_isaac_env
  - ACCEPT_EULA=Y
  - PRIVACY_CONSENT=Y
  - NVIDIA_VISIBLE_DEVICES=all
  - NVIDIA_DRIVER_CAPABILITIES=all
  - DISPLAY=${DISPLAY}
  - QT_X11_NO_MITSHM=1
  - TELEOP_PORT=${TELEOP_PORT:-/dev/ttyACM0}
  - TELEOP_ID=${TELEOP_ID:-leader_arm_1}
  - ISAACLAB=/workspace/isaaclab
  - HUMANOID_ROOT=/workspace/humanoid
  - TASK_ROOT=/workspace/humanoid/autonomy/simulation/so101_vial_task
  - RL_ROOT=/workspace/humanoid/autonomy/simulation/Humanoid_Wato/HumanoidRL

services:
  simulation_isaac:
    build: &simulation_isaac_build
      context: ..
      dockerfile: docker/simulation/isaac_lab/isaac_lab.Dockerfile
      cache_from:
        - "${SIMULATION_ISAAC_IMAGE:?}:${TAG}"
        - "${SIMULATION_ISAAC_IMAGE:?}:main"
    image: "${SIMULATION_ISAAC_IMAGE:?}:${TAG}"
    privileged: true
    gpus: all
    environment: *simulation_isaac_env
    profiles: [deploy]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes: *simulation_isaac_volumes
    network_mode: host
    stdin_open: true
    tty: true
    command: sleep infinity

  simulation_isaac_dev:
    build: *simulation_isaac_build
    image: "${SIMULATION_ISAAC_IMAGE:?}:dev_${TAG}"
    privileged: true
    gpus: all
    environment: *simulation_isaac_env
    profiles: [develop]
    volumes: *simulation_isaac_volumes
    network_mode: host
    stdin_open: true
    tty: true
    command: sleep infinity
