services:
  interfacing:
    build: &interfacing
      context: ..
      dockerfile: docker/interfacing/interfacing.Dockerfile
      cache_from:
        - "${INTERFACING_IMAGE:?}:${TAG}"
        - "${INTERFACING_IMAGE:?}:main"
    image: "${INTERFACING_IMAGE:?}:${TAG}"
    profiles: [deploy, develop]
    command: /bin/bash -c "ros2 launch can can.launch.py"
    privileged: true
    network_mode: host # Allow the container to access the host's network interfaces
    cap_add: # Grant the capability to configure network interfaces
      - NET_ADMIN
    environment:
      # Avoid FastDDS SHM isolation between can_node and docker-exec shells
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
    volumes:
      - /dev:/dev # Allow access to host devices
      - ${MONO_DIR}/autonomy/interfacing:/root/ament_ws/src/interfacing
      # For calibrate_arm.py --write-mapping
      - ${MONO_DIR}/autonomy/behaviour/joint_command/config/hardware_mapping.yaml:/calibration/hardware_mapping.yaml
