services:
  simulation_mj:
    build:
      context: ..
      dockerfile: docker/simulation/mjlabs/mjlabs.Dockerfile
      target: develop
      args:
        USER_UID: "${USER_UID}"
        USER_GID: "${USER_GID}"
        USERNAME: "${USERNAME}"
      cache_from:
        - "${SIMULATION_MJ_IMAGE:?}:${TAG}"
        - "${SIMULATION_MJ_IMAGE:?}:main"
    image: "${SIMULATION_MJ_IMAGE:?}:${TAG}"
    network_mode: "bridge"
    ipc: "none"
    ports:
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - ROS_DOMAIN_ID=0
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${MONO_DIR}/src/simulation:/root/ament_ws/src/simulation
      - ${MONO_DIR}/src/teleop:/root/ament_ws/src/teleop
      - ${MONO_DIR}/src/common_msgs:/root/ament_ws/src/common_msgs
      - ${MONO_DIR}/src/behaviour:/root/ament_ws/src/behaviour