  
services:
  controller: 
    build: &controller_build
      context: ..
      dockerfile: docker/controller/controller.Dockerfile
      cache_from:
        - "${CONTROLLER_IMAGE:?}:${TAG}"
        - "${CONTROLLER_IMAGE:?}:main"
      args:
        BASE_IMAGE: ${BASE_IMAGE_OVERRIDE-}
    image: "${CONTROLLER_IMAGE:?}:${TAG}"
    profiles: [deploy]
    command: /bin/bash -c "ros2 launch controller launch.py"
    volumes:
      - ${MONO_DIR}/autonomy/controller/:/root/ament_ws/src/controller/