left:
  shoulder:
    pitch:
      can_id: 14
      lower_limit: -31.900001525878906
      upper_limit: 41.60000038146973
      direction: 1
      zero_offset: 66.5
      limit_range: true
    roll:
      can_id: 12
      direction: -1
      zero_offset: -85.0999984741211
      lower_limit: -3.0
      upper_limit: 1.9000015258789062
      limit_range: true
    yaw:
      can_id: 11
      lower_limit: -212.2999973297119
      upper_limit: 92.39999961853027
      direction: 1
      zero_offset: -21.100000381469727
      limit_range: true
  elbow:
    pitch:
      can_id: 10
      direction: -1
      zero_offset: -77.5
      lower_limit: -55.10000038146973
      upper_limit: 56.30000305175781
      limit_range: true
    roll:
      can_id: 13
      lower_limit: -46.099998474121094
      upper_limit: 36.0
      direction: 1
      zero_offset: -129.5
      limit_range: true
  wrist:
    pitch:
      can_id: 22
      lower_limit: -90
      upper_limit: 90
      direction: 1
      zero_offset: 0
      limit_range: true
  gripper:
    open_close:
      can_id: 21
      lower_limit: 0
      upper_limit: 100
      direction: 1
      zero_offset: 0
      limit_range: true
