std_msgs/Header header

string name

# Thumb
common_msgs/JointState thumb_cmc
common_msgs/JointState thumb_mcp
common_msgs/JointState thumb_ip

# Index
common_msgs/JointState index_mcp
common_msgs/JointState index_pip
common_msgs/JointState index_dip

# Middle
common_msgs/JointState middle_mcp
common_msgs/JointState middle_pip
common_msgs/JointState middle_dip

# Ring
common_msgs/JointState ring_mcp
common_msgs/JointState ring_pip
common_msgs/JointState ring_dip

# Pinky
common_msgs/JointState pinky_mcp
common_msgs/JointState pinky_pip
common_msgs/JointState pinky_dip