left:
  shoulder:
    pitch:
      can_id: 14
      lower_limit: -9.20001220703125
      upper_limit: 10.699996948242188
      direction: 1
      zero_offset: 185.39999389648438
      limit_range: true
    roll:
      can_id: 12
      direction: -1
      zero_offset: -84.4
      lower_limit: -7.700000000000003
      upper_limit: 3.6999999999999886
      limit_range: true
    yaw:
      can_id: 11
      lower_limit: -11.300003051757812
      upper_limit: 38.19999694824219
      direction: 1
      zero_offset: 177.89999389648438
      limit_range: true
  elbow:
    pitch:
      can_id: 10
      direction: -1
      zero_offset: -105.5
      lower_limit: -37.400001525878906
      upper_limit: 47.19999694824219
      limit_range: true
    roll:
      can_id: 13
      lower_limit: -46.099998474121094
      upper_limit: 36.0
      direction: 1
      zero_offset: -129.5
      limit_range: true
  wrist:
    pitch:
      can_id: 22
      lower_limit: -90
      upper_limit: 90
      direction: 1
      zero_offset: 0
      limit_range: true
  gripper:
    open_close:
      can_id: 21
      lower_limit: 0
      upper_limit: 100
      direction: 1
      zero_offset: 0
      limit_range: true
