"""Generate the racket and shuttle visual meshes (phase 2 assets).

The meshes are procedural (trimesh primitives), so scale and frame conventions
are correct by construction:

- racket: face center at origin, face normal +z, shaft along -y.
- shuttle: skirt-ring center at origin, cork axis +z (cork tip at +z).

Meshes are for eyes only; physics uses the primitives in the MJCF (face box,
shuttle sphere). Swap these for pulled meshes later by overwriting the .obj
files and re-running the alignment check (gate 2.4).

Usage: uv run python scripts/mesh_prep.py
"""

import os
import sys

import numpy as np
import trimesh

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import aero

ASSETS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "scene", "assets")

# racket dimensions (m); head_length comes from params.yaml (mesh-scale anchor)
HEAD_WIDTH = 0.22
SHAFT_R = 0.005
HANDLE_R = 0.0145
HANDLE_LEN = 0.13
TOTAL_LEN = 0.665

# shuttle dimensions (m)
SKIRT_R = 0.0325
SKIRT_DEPTH = 0.055     # skirt ring to cork base
CORK_R = 0.0135
CORK_LEN = 0.030


def _rot_x(deg):
    return trimesh.transformations.rotation_matrix(np.radians(deg), [1, 0, 0])


def build_racket(head_length: float) -> trimesh.Trimesh:
    a_y = head_length / 2.0        # head half-axis along shaft
    a_x = HEAD_WIDTH / 2.0
    tube = 0.007

    # head hoop: unit torus scaled into an ellipse in the xy plane
    hoop = trimesh.creation.torus(major_radius=1.0, minor_radius=tube,
                                  major_sections=64, minor_sections=12)
    hoop.apply_scale([a_x, a_y, 1.0])

    # string bed: thin disc filling the hoop at z=0
    strings = trimesh.creation.cylinder(radius=1.0, height=0.0015, sections=48)
    strings.apply_scale([a_x - tube, a_y - tube, 1.0])

    # shaft: from head bottom (-a_y) to handle start
    butt_y = -(TOTAL_LEN - a_y)
    shaft_len = (TOTAL_LEN - head_length) - HANDLE_LEN
    shaft = trimesh.creation.cylinder(radius=SHAFT_R, height=shaft_len, sections=16)
    shaft.apply_transform(_rot_x(90))  # z -> y
    shaft.apply_translation([0, -a_y - shaft_len / 2.0, 0])

    handle = trimesh.creation.cylinder(radius=HANDLE_R, height=HANDLE_LEN, sections=16)
    handle.apply_transform(_rot_x(90))
    handle.apply_translation([0, butt_y + HANDLE_LEN / 2.0, 0])

    return trimesh.util.concatenate([hoop, strings, shaft, handle])


def build_shuttle() -> trimesh.Trimesh:
    # skirt: open cone from the wide ring at z=0 to the cork base
    ring = np.array([[SKIRT_R * np.cos(t), SKIRT_R * np.sin(t), 0.0]
                     for t in np.linspace(0, 2 * np.pi, 33)[:-1]])
    top = np.array([[CORK_R * np.cos(t), CORK_R * np.sin(t), SKIRT_DEPTH]
                    for t in np.linspace(0, 2 * np.pi, 33)[:-1]])
    n = len(ring)
    verts = np.vstack([ring, top])
    faces = []
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, n + i])
        faces.append([j, n + j, n + i])
        # double-sided so the open cone renders from inside too
        faces.append([j, i, n + i])
        faces.append([n + j, j, n + i])
    skirt = trimesh.Trimesh(vertices=verts, faces=np.array(faces), process=False)

    cork_cyl = trimesh.creation.cylinder(radius=CORK_R, height=CORK_LEN - CORK_R,
                                         sections=24)
    cork_cyl.apply_translation([0, 0, SKIRT_DEPTH + (CORK_LEN - CORK_R) / 2.0])
    cork_cap = trimesh.creation.icosphere(subdivisions=2, radius=CORK_R)
    cork_cap.apply_translation([0, 0, SKIRT_DEPTH + CORK_LEN - CORK_R])
    return trimesh.util.concatenate([skirt, cork_cyl, cork_cap])


def main():
    os.makedirs(ASSETS, exist_ok=True)
    params = aero.load_params()
    head_length = params["racket"]["head_length"]

    racket = build_racket(head_length)
    racket.export(os.path.join(ASSETS, "racket_vis.obj"))
    print(f"racket_vis.obj: {len(racket.faces)} tris, "
          f"extent y {racket.bounds[0][1]:.3f}..{racket.bounds[1][1]:.3f}")

    shuttle = build_shuttle()
    shuttle.export(os.path.join(ASSETS, "shuttle_vis.obj"))
    print(f"shuttle_vis.obj: {len(shuttle.faces)} tris, "
          f"extent z {shuttle.bounds[0][2]:.3f}..{shuttle.bounds[1][2]:.3f}")

    lic = os.path.join(ASSETS, "LICENSES.md")
    with open(lic, "w") as f:
        f.write(
            "# Asset licenses\n\n"
            "- `racket_vis.obj`, `shuttle_vis.obj`: procedurally generated by "
            "`scripts/mesh_prep.py` (trimesh primitives). No external sources; "
            "same license as the repository.\n"
            "- Arm meshes are referenced in place from "
            "`autonomy/simulation/Humanoid_Wato/arm_assembly/meshes/right_arm/` "
            "and are project assets.\n"
        )
    print("wrote", lic)


if __name__ == "__main__":
    main()
