#!/usr/bin/env python3
"""Generate procedural MJCF LEGO piece assets (bricks, plates, tiles).

Regenerate everything after editing this file:

    python3 assets/lego/generate.py

Each piece is a solid box + (for bricks/plates) a grid of cylinder studs,
sized to real LEGO measurements. Tiles are the same footprint/height as a
plate but with no studs on top.
"""

import pathlib

PITCH = 0.008  # stud spacing, m
GAP = 0.0002  # constant footprint tolerance (both axes), m
BRICK_HEIGHT = 0.0096  # 3 plates tall
PLATE_HEIGHT = 0.0032  # 1 plate tall
STUD_RADIUS = 0.0024
STUD_HALF_HEIGHT = 0.00085
STUD_EMBED = 0.0008  # sinks the stud slightly into the body to avoid a coincident seam

KINDS = {
    "brick": {"height": BRICK_HEIGHT, "studded": True},
    "plate": {"height": PLATE_HEIGHT, "studded": True},
    "tile": {"height": PLATE_HEIGHT, "studded": False},
}

PIECES = [
    # (kind, studs_x, studs_y)
    # Note: the original 2x4 brick lives separately as lego_2x4.xml (hand-authored
    # before this generator existed) and is intentionally not duplicated here.
    ("brick", 2, 2),
    ("brick", 2, 1),
    ("plate", 4, 2),
    ("plate", 2, 2),
    ("tile", 2, 2),
    ("tile", 2, 1),
]

COLOR_BY_KIND = {
    "brick": ("lego_red", "0.77 0.06 0.05 1"),
    "plate": ("lego_yellow", "0.93 0.75 0.05 1"),
    "tile": ("lego_blue", "0.0 0.2 0.55 1"),
}


def footprint_half(n_studs: float) -> float:
    return (n_studs * PITCH - GAP) / 2


def studs(name, height, n_x, n_y):
    top = height
    z = top + STUD_HALF_HEIGHT - STUD_EMBED
    lines = []
    xs = [(i - (n_x - 1) / 2) * PITCH for i in range(n_x)]
    ys = [(j - (n_y - 1) / 2) * PITCH for j in range(n_y)]
    for i, x in enumerate(xs):
        for j, y in enumerate(ys):
            lines.append(
                f'      <geom class="{name}/stud" name="{name}_stud_{i}{j}" '
                f'size="{STUD_RADIUS:g} {STUD_HALF_HEIGHT:g}" pos="{x:g} {y:g} {z:g}"/>'
            )
    return "\n".join(lines)


def piece_xml(kind, n_x, n_y):
    name = f"lego_{kind}_{n_x}x{n_y}"
    cfg = KINDS[kind]
    height = cfg["height"]
    hx = footprint_half(n_x)
    hy = footprint_half(n_y)
    hz = height / 2
    material, rgba = COLOR_BY_KIND[kind]

    stud_block = ""
    stud_default = ""
    if cfg["studded"]:
        stud_block = "\n\n" + studs(name, height, n_x, n_y)
        stud_default = f'\n      <default class="{name}/stud">\n        <geom type="cylinder"/>\n      </default>'

    return f"""<mujoco model="{name}">
  <!--
    {n_x}x{n_y} LEGO {kind}, built from MJCF primitives (no mesh files needed).
    Generated by assets/lego/generate.py -- edit that file, not this one.

    Include this file inside a <worldbody> to splice in one piece, e.g.:

      <mujoco>
        <include file="{name}.xml"/>
        <worldbody> ... </worldbody>
      </mujoco>

    Rename/duplicate the <body>/geom names if you spawn more than one piece
    in the same scene (MJCF requires unique names).
  -->
  <compiler angle="radian"/>

  <default>
    <default class="{name}">
      <!-- density is tuned down from ABS's real ~1050 kg/m3 so the solid
           primitive body (no hollow underside) lands near a real piece's mass -->
      <geom type="box" material="{material}" density="500" friction="0.9 0.02 0.001"/>{stud_default}
    </default>
  </default>

  <asset>
    <material name="{material}" rgba="{rgba}"/>
  </asset>

  <worldbody>
    <body name="{name}" childclass="{name}">
      <freejoint name="{name}_freejoint"/>

      <!-- {kind} body: {n_x} studs long (x) x {n_y} studs wide (y) x {height * 1000:g}mm tall (z) -->
      <!-- mass/inertia are left to MuJoCo, computed from geom volume x density above -->
      <geom name="{name}_body" size="{hx:g} {hy:g} {hz:g}" pos="0 0 {hz:g}"/>{stud_block}
    </body>
  </worldbody>
</mujoco>
"""


def scene_xml(name):
    return f"""<mujoco model="{name}_scene">
  <!--
    Standalone viewer scene for the {name} asset.
    Quick look:
      python -m mujoco.viewer --mjcf assets/lego/scene_{name}.xml
  -->
  <option timestep="0.002" gravity="0 0 -9.81"/>

  <visual>
    <headlight ambient="0.4 0.4 0.4" diffuse="0.6 0.6 0.6" specular="0.1 0.1 0.1"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="512"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
              markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.1"/>
  </asset>

  <worldbody>
    <light pos="0.2 0.2 0.3" dir="-0.5 -0.5 -1" diffuse="0.8 0.8 0.8"/>
    <geom name="floor" type="plane" size="0.5 0.5 0.05" material="groundplane"/>
  </worldbody>

  <include file="{name}.xml"/>

  <keyframe>
    <key name="dropped" qpos="0 0 0.05 1 0 0 0"/>
  </keyframe>
</mujoco>
"""


def main():
    out_dir = pathlib.Path(__file__).parent
    names = []
    for kind, n_x, n_y in PIECES:
        name = f"lego_{kind}_{n_x}x{n_y}"
        names.append(name)
        (out_dir / f"{name}.xml").write_text(piece_xml(kind, n_x, n_y))
        (out_dir / f"scene_{name}.xml").write_text(scene_xml(name))
        print(f"wrote {name}.xml, scene_{name}.xml")
    return names


if __name__ == "__main__":
    main()
